apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checks-out
  namespace: checks-out
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: checks-out.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checks-out
                port:
                  number: 80
  tls:
    - hosts:
        - checks-out.example.com
      secretName: checks-out-tls
